package org.libsdl.app;

import android.app.Activity;
import android.content.ClipData;
import android.content.Intent;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Bundle;
import android.provider.DocumentsContract;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Small Android front-end for the existing native CPKREDIR/ModLoader implementation.
 *
 * The manager never interprets or copies mod payloads. It discovers ordinary HMM/UMM
 * mod.ini files in app-owned folders and atomically writes the cpkredir.ini/ModsDB.ini
 * format already consumed by ModLoader::Init(). Changes therefore take effect only on
 * the next game process start and remain compatible with desktop mod tooling.
 */
public final class ModManagerActivity extends Activity {
    private static final String GENERATED_HEADER = "; Generated by Unleashed Android Mod Manager";
    private static final String MOD_DATABASE_NAME = "android_mods_db.ini";
    private static final int MAX_SCAN_DEPTH = 4;
    private static final int MAX_SCANNED_FILES = 1000;

    // Built-in codes understood by the native loader (config_def.h [Codes] section).
    // Names must match exactly - the loader turns on the matching hidden config value
    // at boot. SkipIntroLogos is intentionally omitted: the launcher already exposes
    // it. Codes found in the database but absent here are preserved and still toggleable.
    private static final String[][] CODE_DEFS = {
        { "AllowCancellingUnleash", "Allow cancelling Unleash" },
        { "DisableAutoSaveWarning", "Disable auto-save warning" },
        { "DisableBoostFilter", "Disable boost filter" },
        { "DisableDLCIcon", "Disable DLC icon" },
        { "DisableDPadMovement", "Disable D-pad movement" },
        { "FixEggmanlandUsingEventGalleryTransition", "Fix Eggmanland event-gallery transition" },
        { "FixUnleashOutOfControlDrain", "Fix Unleash out-of-control drain" },
        { "HomingAttackOnJump", "Homing attack on jump" },
        { "SaveScoreAtCheckpoints", "Save score at checkpoints" },
        { "UseAlternateTitle", "Use alternate title" },
        { "UseArrowsForTimeOfDayTransition", "Use arrows for time-of-day transition" },
    };

    private final List<ModEntry> mods = new ArrayList<>();
    private LinearLayout modList;
    private TextView status;
    private int scannedFiles;
    private final LinkedHashSet<String> enabledCodes = new LinkedHashSet<>();

    private static final class ModEntry {
        final File iniFile;
        final String canonicalPath;
        final String title;
        final File configSchemaFile;
        boolean enabled;

        ModEntry(File iniFile, String canonicalPath, String title,
                File configSchemaFile) {
            this.iniFile = iniFile;
            this.canonicalPath = canonicalPath;
            this.title = title;
            this.configSchemaFile = configSchemaFile;
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        LinearLayout page = new LinearLayout(this);
        page.setOrientation(LinearLayout.VERTICAL);
        page.setPadding(dp(16), dp(16), dp(16), dp(12));

        TextView title = new TextView(this);
        title.setText(R.string.mod_manager_title);
        title.setTextSize(24);
        title.setTypeface(Typeface.DEFAULT, Typeface.BOLD);
        page.addView(title, matchWrap());

        TextView hint = new TextView(this);
        hint.setText(R.string.mod_manager_hint);
        hint.setPadding(0, dp(8), 0, dp(10));
        page.addView(hint, matchWrap());

        LinearLayout actions = new LinearLayout(this);
        actions.setOrientation(LinearLayout.HORIZONTAL);

        Button openFiles = new Button(this);
        openFiles.setText(R.string.mod_manager_open_files);
        openFiles.setOnClickListener(view -> openGameFiles());
        actions.addView(openFiles, weightedWrap());

        Button refresh = new Button(this);
        refresh.setText(R.string.mod_manager_refresh);
        refresh.setOnClickListener(view -> reload());
        actions.addView(refresh, weightedWrap());
        page.addView(actions, matchWrap());

        ScrollView scroll = new ScrollView(this);
        modList = new LinearLayout(this);
        modList.setOrientation(LinearLayout.VERTICAL);
        scroll.addView(modList, matchWrap());
        page.addView(scroll, new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT, 0, 1.0f));

        status = new TextView(this);
        status.setPadding(0, dp(8), 0, dp(4));
        page.addView(status, matchWrap());

        Button save = new Button(this);
        save.setText(R.string.mod_manager_save);
        save.setOnClickListener(view -> saveSelection());
        page.addView(save, matchWrap());

        setContentView(page);
        reload();
    }

    private void reload() {
        mods.clear();
        scannedFiles = 0;

        File activeGameRoot = getActiveGameRoot();
        File gameMods = new File(activeGameRoot, "mods");
        File transferMods = getExternalFilesDir(null) != null
            ? new File(getExternalFilesDir(null), "mods")
            : gameMods;
        gameMods.mkdirs();
        // 0.3.0 also auto-created a second mods folder in the transfer root, which
        // confused users about where mods belong (issue #42). Only the game-root folder
        // is created now; the transfer one is removed when empty and still scanned when
        // the user actually put mods in it.
        if (!transferMods.equals(gameMods)) {
            transferMods.delete();
        }

        Map<String, ModEntry> discovered = new LinkedHashMap<>();
        scanForMods(gameMods, 0, discovered);
        try {
            if (transferMods.isDirectory()
                    && !gameMods.getCanonicalFile().equals(transferMods.getCanonicalFile())) {
                scanForMods(transferMods, 0, discovered);
            }
        } catch (IOException exception) {
            if (transferMods.isDirectory()) {
                scanForMods(transferMods, 0, discovered);
            }
        }

        File userDirectory = new File(AppStorage.configRoot(this), ".config/UnleashedRecomp");
        File managerDatabase = new File(userDirectory, MOD_DATABASE_NAME);
        File sourceDatabase = findSourceDatabase(userDirectory, managerDatabase);
        Map<String, Map<String, String>> sourceIni = readIni(sourceDatabase);
        enabledCodes.clear();
        Map<String, String> oldCodes = sourceIni.get("Codes");
        if (oldCodes != null) {
            int codeCount;
            try {
                codeCount = Integer.parseInt(oldCodes.getOrDefault("CodeCount", "0"));
            } catch (NumberFormatException exception) {
                codeCount = 0;
            }
            for (int index = 0; index < codeCount; index++) {
                String name = oldCodes.get("Code" + index);
                if (name != null && !name.trim().isEmpty()) {
                    enabledCodes.add(name.trim());
                }
            }
        }
        List<String> activePaths = readActivePaths(sourceIni);
        Set<String> enabledPaths = new HashSet<>(activePaths);

        // Keep a previously configured active mod visible even when its mod.ini lives
        // outside the two new conventional folders (for example a migrated install).
        for (String path : activePaths) {
            if (discovered.containsKey(path)) {
                continue;
            }
            File iniFile = new File(path);
            Map<String, Map<String, String>> ini = readIni(iniFile);
            if (iniFile.isFile() && isSupportedModIni(ini)) {
                discovered.put(path, new ModEntry(iniFile, path, findTitle(iniFile, ini),
                    findConfigSchema(iniFile, ini)));
            }
        }

        // Keep the saved active order first, then append newly discovered/inactive mods
        // alphabetically so Refresh never silently changes priority.
        for (String path : activePaths) {
            ModEntry entry = discovered.remove(path);
            if (entry != null) {
                entry.enabled = true;
                mods.add(entry);
            }
        }

        List<ModEntry> remaining = new ArrayList<>(discovered.values());
        remaining.sort(Comparator.comparing(entry -> entry.title.toLowerCase(Locale.ROOT)));
        for (ModEntry entry : remaining) {
            entry.enabled = enabledPaths.contains(entry.canonicalPath);
            mods.add(entry);
        }

        rebuildRows();
        status.setText(getString(R.string.mod_manager_found, mods.size()));
    }

    private void scanForMods(File directory, int depth, Map<String, ModEntry> result) {
        if (depth > MAX_SCAN_DEPTH || scannedFiles >= MAX_SCANNED_FILES || !directory.isDirectory()) {
            return;
        }

        File[] children = directory.listFiles();
        if (children == null) {
            return;
        }
        List<File> sorted = new ArrayList<>();
        Collections.addAll(sorted, children);
        sorted.sort(Comparator.comparing(File::getName, String.CASE_INSENSITIVE_ORDER));

        // Parse the ini files of this level before descending: "mod" sorts before
        // "mod.ini", so a mod whose content folders hold thousands of files used to
        // exhaust the scan budget before its own mod.ini was ever read, hiding it
        // and every mod after it (issue #58).
        boolean foundModHere = false;
        for (File child : sorted) {
            if (!child.isFile() || !child.getName().toLowerCase(Locale.ROOT).endsWith(".ini")
                    || Files.isSymbolicLink(child.toPath())) {
                continue;
            }

            scannedFiles++;
            Map<String, Map<String, String>> ini = readIni(child);
            if (!isSupportedModIni(ini)) {
                continue;
            }

            try {
                String canonicalPath = child.getCanonicalPath();
                if (canonicalPath.indexOf('\n') >= 0 || canonicalPath.indexOf('\r') >= 0 ||
                    canonicalPath.indexOf('"') >= 0) {
                    continue;
                }
                result.put(canonicalPath, new ModEntry(child, canonicalPath, findTitle(child, ini),
                    findConfigSchema(child, ini)));
                foundModHere = true;
            } catch (IOException ignored) {
                // A path that cannot be canonicalised cannot be handed safely to ModLoader.
            }
        }

        // A mod's folder only contains its own content; other mods never nest inside
        // one, so skipping the descent keeps the scan budget for sibling mods.
        if (foundModHere) {
            return;
        }

        for (File child : sorted) {
            if (scannedFiles >= MAX_SCANNED_FILES) {
                break;
            }
            if (Files.isSymbolicLink(child.toPath())) {
                continue;
            }
            if (child.isDirectory()) {
                scanForMods(child, depth + 1, result);
            } else if (!child.getName().toLowerCase(Locale.ROOT).endsWith(".ini")) {
                scannedFiles++;
            }
        }
    }

    private static boolean isSupportedModIni(Map<String, Map<String, String>> ini) {
        return ini.containsKey("Details") || ini.containsKey("Filesystem") ||
            (ini.containsKey("Main") &&
                (ini.get("Main").containsKey("IncludeDirCount") ||
                 ini.get("Main").containsKey("IncludeDir0")));
    }

    private static String findTitle(File file, Map<String, Map<String, String>> ini) {
        String[] sections = { "Desc", "Details", "Main" };
        String[] keys = { "Title", "Name" };
        for (String section : sections) {
            Map<String, String> values = ini.get(section);
            if (values == null) {
                continue;
            }
            for (String key : keys) {
                String value = values.get(key);
                if (value != null && !value.trim().isEmpty()) {
                    return value.trim();
                }
            }
        }
        File parent = file.getParentFile();
        return parent != null ? parent.getName() : file.getName();
    }

    private void rebuildRows() {
        modList.removeAllViews();
        if (mods.isEmpty()) {
            TextView empty = new TextView(this);
            empty.setText(R.string.mod_manager_empty);
            empty.setPadding(0, dp(24), 0, dp(24));
            empty.setGravity(Gravity.CENTER);
            modList.addView(empty, matchWrap());
            addCodesSection();
            return;
        }

        for (int index = 0; index < mods.size(); index++) {
            final ModEntry entry = mods.get(index);
            LinearLayout row = new LinearLayout(this);
            row.setOrientation(LinearLayout.HORIZONTAL);
            row.setGravity(Gravity.CENTER_VERTICAL);

            CheckBox enabled = new CheckBox(this);
            enabled.setText(entry.title + "\n" + entry.iniFile.getParent());
            enabled.setChecked(entry.enabled);
            enabled.setOnCheckedChangeListener((button, checked) -> entry.enabled = checked);
            row.addView(enabled, new LinearLayout.LayoutParams(0,
                LinearLayout.LayoutParams.WRAP_CONTENT, 1.0f));

            final int rowIndex = index;
            if (entry.configSchemaFile != null) {
                Button settings = new Button(this);
                settings.setText("⚙");
                settings.setContentDescription(getString(R.string.mod_settings_open, entry.title));
                settings.setOnClickListener(view -> openModSettings(entry));
                row.addView(settings, squareButton());
            }

            Button up = new Button(this);
            up.setText("↑");
            up.setEnabled(index > 0);
            up.setOnClickListener(view -> move(rowIndex, -1));
            row.addView(up, squareButton());

            Button down = new Button(this);
            down.setText("↓");
            down.setEnabled(index + 1 < mods.size());
            down.setOnClickListener(view -> move(rowIndex, 1));
            row.addView(down, squareButton());

            modList.addView(row, matchWrap());
        }

        addCodesSection();
    }

    private void openModSettings(ModEntry entry) {
        Intent intent = new Intent(this, ModSettingsActivity.class);
        intent.putExtra(ModSettingsActivity.EXTRA_TITLE, entry.title);
        intent.putExtra(ModSettingsActivity.EXTRA_ROOT, entry.iniFile.getParentFile().getAbsolutePath());
        intent.putExtra(ModSettingsActivity.EXTRA_SCHEMA, entry.configSchemaFile.getAbsolutePath());
        startActivity(intent);
    }

    private static File findConfigSchema(File modIni,
            Map<String, Map<String, String>> ini) {
        Map<String, String> main = ini.get("Main");
        String relative = main != null ? main.get("ConfigSchemaFile") : null;
        if (relative == null || relative.trim().isEmpty()) return null;
        try {
            File root = modIni.getParentFile().getCanonicalFile();
            File schema = new File(root, relative.trim()).getCanonicalFile();
            if (!schema.getPath().startsWith(root.getPath() + File.separator) ||
                    !schema.isFile() || schema.length() <= 0 || schema.length() > 1024 * 1024) {
                return null;
            }
            return schema;
        } catch (IOException exception) {
            return null;
        }
    }

    // Built-in cheat/patch codes (issue #75). The native ModLoader reads these from the
    // mods database [Codes] section at boot; unknown codes already in the database are
    // shown as-is so they can be turned off without hand-editing the file.
    private void addCodesSection() {
        TextView header = new TextView(this);
        header.setText(R.string.mod_manager_codes);
        header.setTypeface(Typeface.DEFAULT, Typeface.BOLD);
        header.setPadding(0, dp(18), 0, dp(2));
        modList.addView(header, matchWrap());

        TextView hint = new TextView(this);
        hint.setText(R.string.mod_manager_codes_hint);
        hint.setPadding(0, 0, 0, dp(6));
        modList.addView(hint, matchWrap());

        Set<String> known = new HashSet<>();
        for (String[] def : CODE_DEFS) {
            final String name = def[0];
            known.add(name);
            CheckBox box = new CheckBox(this);
            box.setText(def[1]);
            box.setChecked(enabledCodes.contains(name));
            box.setOnCheckedChangeListener((button, checked) -> {
                if (checked) {
                    enabledCodes.add(name);
                } else {
                    enabledCodes.remove(name);
                }
            });
            modList.addView(box, matchWrap());
        }

        for (String name : new ArrayList<>(enabledCodes)) {
            if (known.contains(name)) {
                continue;
            }
            final String extra = name;
            CheckBox box = new CheckBox(this);
            box.setText(name);
            box.setChecked(true);
            box.setOnCheckedChangeListener((button, checked) -> {
                if (checked) {
                    enabledCodes.add(extra);
                } else {
                    enabledCodes.remove(extra);
                }
            });
            modList.addView(box, matchWrap());
        }
    }

    private void move(int index, int offset) {
        int target = index + offset;
        if (target < 0 || target >= mods.size()) {
            return;
        }
        Collections.swap(mods, index, target);
        rebuildRows();
    }

    private void saveSelection() {
        File userDirectory = new File(AppStorage.configRoot(this), ".config/UnleashedRecomp");
        if (!userDirectory.isDirectory() && !userDirectory.mkdirs()) {
            showError(getString(R.string.mod_manager_error_directory, userDirectory));
            return;
        }

        File database = new File(userDirectory, MOD_DATABASE_NAME);
        File cpkredir = new File(userDirectory, "cpkredir.ini");
        File backup = new File(userDirectory, "cpkredir.pre_android_manager.ini");

        try {
            if (cpkredir.isFile() && !backup.exists() && !isGeneratedByManager(cpkredir)) {
                Files.copy(cpkredir.toPath(), backup.toPath(), StandardCopyOption.COPY_ATTRIBUTES);
            }

            StringBuilder db = new StringBuilder(GENERATED_HEADER).append('\n');
            db.append("[Main]\n");
            int activeIndex = 0;
            for (int index = 0; index < mods.size(); index++) {
                if (mods.get(index).enabled) {
                    db.append("ActiveMod").append(activeIndex++).append("=mod").append(index).append('\n');
                }
            }
            db.append("ActiveModCount=").append(activeIndex).append("\n\n[Mods]\n");
            for (int index = 0; index < mods.size(); index++) {
                db.append("mod").append(index).append("=\"")
                    .append(mods.get(index).canonicalPath).append("\"\n");
            }
            db.append("\n[Codes]\n");
            db.append("CodeCount=").append(enabledCodes.size()).append('\n');
            int codeIndex = 0;
            for (String code : enabledCodes) {
                db.append("Code").append(codeIndex++).append('=').append(code).append('\n');
            }
            writeAtomic(database, db.toString());

            // Retain unrelated core-loader settings (notably save redirection and log
            // mode) when taking ownership of an existing desktop-generated config.
            Map<String, Map<String, String>> oldConfig = readIni(cpkredir);
            Map<String, String> cpkredirValues = oldConfig.get("CPKREDIR");
            LinkedHashMap<String, String> mergedValues = new LinkedHashMap<>();
            if (cpkredirValues != null) {
                mergedValues.putAll(cpkredirValues);
            }
            mergedValues.put("Enabled", "true");
            mergedValues.put("ModsDbIni", database.getCanonicalPath());

            StringBuilder config = new StringBuilder(GENERATED_HEADER).append("\n[CPKREDIR]\n");
            for (Map.Entry<String, String> value : mergedValues.entrySet()) {
                String encoded = encodeIniValue(value.getValue());
                if (encoded != null) {
                    config.append(value.getKey()).append('=').append(encoded).append('\n');
                }
            }
            writeAtomic(cpkredir, config.toString());

            status.setText(getString(R.string.mod_manager_saved, activeIndex));
            Toast.makeText(this, R.string.mod_manager_restart, Toast.LENGTH_LONG).show();
        } catch (IOException exception) {
            showError(getString(R.string.mod_manager_error_save, exception.getMessage()));
        }
    }

    private void openGameFiles() {
        try {
            Uri directory = DocumentsContract.buildDocumentUri(
                getPackageName() + ".documents", "game:");
            // VIEW opens the full Files activity (copy/rename/delete), unlike
            // OPEN_DOCUMENT_TREE which is only a destination picker and is redirected
            // to device storage by several Android 16 DocumentsUI builds.
            Intent intent = new Intent(Intent.ACTION_VIEW);
            intent.setDataAndType(directory, "vnd.android.document/directory");
            intent.setClipData(ClipData.newRawUri("Unleashed Recomp files", directory));
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION |
                Intent.FLAG_GRANT_WRITE_URI_PERMISSION |
                Intent.FLAG_ACTIVITY_NEW_DOCUMENT);
            startActivity(intent);
        } catch (Exception exception) {
            showError(getString(R.string.mod_manager_error_files));
        }
    }

    private File getActiveGameRoot() {
        return AppStorage.activeGameRoot(this);
    }

    private static File findSourceDatabase(File userDirectory, File managerDatabase) {
        if (managerDatabase.isFile()) {
            return managerDatabase;
        }
        Map<String, Map<String, String>> config = readIni(new File(userDirectory, "cpkredir.ini"));
        Map<String, String> values = config.get("CPKREDIR");
        String configuredPath = values != null ? values.get("ModsDbIni") : null;
        if (configuredPath == null || configuredPath.isEmpty()) {
            return managerDatabase;
        }
        File configured = new File(configuredPath);
        return configured.isAbsolute() ? configured : new File(userDirectory, configuredPath);
    }

    private List<String> readActivePaths(Map<String, Map<String, String>> ini) {
        Map<String, String> main = ini.get("Main");
        Map<String, String> paths = ini.get("Mods");
        if (main == null || paths == null) {
            return Collections.emptyList();
        }

        int count;
        try {
            count = Integer.parseInt(main.getOrDefault("ActiveModCount", "0"));
        } catch (NumberFormatException exception) {
            count = 0;
        }

        List<String> result = new ArrayList<>();
        for (int index = 0; index < count; index++) {
            String id = main.get("ActiveMod" + index);
            String path = id != null ? paths.get(id) : null;
            if (path == null) {
                continue;
            }
            try {
                result.add(new File(path).getCanonicalPath());
            } catch (IOException ignored) {
            }
        }
        return result;
    }

    private static Map<String, Map<String, String>> readIni(File file) {
        Map<String, Map<String, String>> result = new LinkedHashMap<>();
        if (!file.isFile()) {
            return result;
        }

        String section = "";
        result.put(section, new LinkedHashMap<>());
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(
            new FileInputStream(file), StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith(";") || line.startsWith("#")) {
                    continue;
                }
                if (line.startsWith("[") && line.endsWith("]")) {
                    section = line.substring(1, line.length() - 1).trim();
                    result.computeIfAbsent(section, unused -> new LinkedHashMap<>());
                    continue;
                }
                int equals = line.indexOf('=');
                if (equals > 0) {
                    String value = line.substring(equals + 1).trim();
                    if (value.length() >= 2 && value.charAt(0) == '"' &&
                        value.charAt(value.length() - 1) == '"') {
                        value = value.substring(1, value.length() - 1);
                    }
                    result.get(section).put(line.substring(0, equals).trim(), value);
                }
            }
        } catch (IOException ignored) {
            result.clear();
        }
        return result;
    }

    private static boolean isGeneratedByManager(File file) {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(
            new FileInputStream(file), StandardCharsets.UTF_8))) {
            return GENERATED_HEADER.equals(reader.readLine());
        } catch (IOException exception) {
            return false;
        }
    }

    private static String encodeIniValue(String value) {
        if (value.indexOf('"') >= 0) {
            // The native parser has no quote escaping. Existing unsupported values are
            // omitted instead of producing a syntactically ambiguous line; the complete
            // original config remains in cpkredir.pre_android_manager.ini.
            return null;
        }
        for (int index = 0; index < value.length(); index++) {
            if (Character.isWhitespace(value.charAt(index))) {
                return '"' + value + '"';
            }
        }
        return value;
    }

    private static void writeAtomic(File target, String contents) throws IOException {
        File temporary = new File(target.getParentFile(), target.getName() + ".tmp");
        try (FileOutputStream output = new FileOutputStream(temporary);
             OutputStreamWriter writer = new OutputStreamWriter(output, StandardCharsets.UTF_8)) {
            writer.write(contents);
            writer.flush();
            output.getFD().sync();
        }

        try {
            Files.move(temporary.toPath(), target.toPath(),
                StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } catch (AtomicMoveNotSupportedException exception) {
            Files.move(temporary.toPath(), target.toPath(), StandardCopyOption.REPLACE_EXISTING);
        } finally {
            Files.deleteIfExists(temporary.toPath());
        }
    }

    private void showError(String message) {
        status.setText(message);
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }

    private static LinearLayout.LayoutParams matchWrap() {
        return new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
    }

    private static LinearLayout.LayoutParams weightedWrap() {
        return new LinearLayout.LayoutParams(
            0, LinearLayout.LayoutParams.WRAP_CONTENT, 1.0f);
    }

    private LinearLayout.LayoutParams squareButton() {
        return new LinearLayout.LayoutParams(dp(52), LinearLayout.LayoutParams.WRAP_CONTENT);
    }
}
